name: GitHub Actions Demo
on: [workflow_dispatch, push]

jobs:
  initialize_repo:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Create Issue
        run: |
          ls -la
