name: GitHub Actions Demo
on: [workflow_dispatch]

jobs:
  initialize_repo:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }} || github.event.schedule != '0 15 6 ? * MON *'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: My First
        run: |
          ls -la
